language: python
sudo: false

env:
  matrix:
    - LUA="luajit @"
    - LUA="luajit 2.0"
    - LUA="luajit 2.1"
  global:
    - LD_LIBRARY_PATH="$HOME/.local/lib"

branches:
  only:
    - master

before_install:
  - pip install hererocks
  - hererocks ~/hererocks -r^ --$LUA
  - export PATH=$PATH:~/hererocks/bin
  - eval `luarocks path --bin`
  - luarocks install luacheck
  - luarocks install luacov-coveralls
  - luarocks install lua_cliargs 2.5-5
  - luarocks install busted 2.0.rc10-0
  - ./.ci.sh

install:
  - luarocks install --only-deps rockspec/bpf-scm-1.rockspec

script:
  - luacheck .
  - busted -c

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: change

cache:
  directories:
    - $HOME/.cache/hererocks
    - $HOME/.local
